package:
    name: HydroModelBuilder
    version: "0.2"

source:
    git_url: https://github.com/daniel-partington/HydroModelBuilder.git
    sha1: 4da7b80873e0eedb25be11be849a26220cad402c

build:
    number: 0

extra:
    channels:
        - conda-forge

requirements:
  build:
    - gdal
    - geos
    - proj4
    - numpy
    - pandas
    - openpyxl
    - flopy
    - nose
  run:
    - gdal
    - geos
    - proj4
    - numpy
    - pandas
    - openpyxl
    - flopy
    - nose

about:
    license: Copyright
